##############################################
# FILE GENERATED AUTOMATICALLY FROM TERRAFORM
# THIS FILE SHOULD NOT BE EDITED BY HAND
##############################################

name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      HUSKY_SKIP_HOOKS: 1
      HUSKY: 0
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Setup node ⚙️
        uses: actions/setup-node@v2
      - name: Install ⚙️️
        run: npm ci
      - name: Build 🔧
        run: npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: "."
